apiVersion: v1
kind: Service
metadata:
  name: projectpulse-backend
  namespace: projectpulse
spec:
  selector:
    app.kubernetes.io/name: projectpulse-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
