apiVersion: batch/v1
kind: Job
metadata:
  name: projectpulse-migrate
  namespace: projectpulse
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: migrate
          image: projectpulse-backend:latest
          imagePullPolicy: IfNotPresent
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: projectpulse-config
            - secretRef:
                name: projectpulse-secret
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 250m
              memory: 256Mi
