apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projectpulse
  namespace: projectpulse
spec:
  ingressClassName: nginx
  rules:
    - host: projectpulse.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: projectpulse-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: projectpulse-web
                port:
                  number: 3000
