apiVersion: v1
kind: Service
metadata:
  name: projectpulse-postgres
  namespace: projectpulse
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: projectpulse-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
