apiVersion: v1
kind: Service
metadata:
  name: projectpulse-web
  namespace: projectpulse
spec:
  selector:
    app.kubernetes.io/name: projectpulse-web
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
